nav:
  # - 原仓库说明: 00-before-the-beginning
  - 事前准备: 01-first-steps.md
  - 游戏循环: 02-the-game-loop.md
  - 我们的第一个三角形: 03-our-first-triangle.md
  - 渲染: 04-more-on-render.md
  - 透视投影: 05-perspective-projection.md
  - 进入三维世界: 06-going-3D.md
  - 纹理: 07-textures.md
  - 摄像机: 08-camera.md
  - 加载更复杂的模型: 09-loading-more-complex-models.md
  - GUI: 10-GUI.md
  - ERROR: 11-ERROR.md
  - 天空盒与一些优化: 12-sky-box.md
  - 雾: 13-fog.md
  - 法线贴图: 14-normal-mapping.md
  - 动画: 15-animations.md
  - 音效: 16-audio.md
  - 阴影: 17-shadows.md
  - 三维物体选取: 18-3D-object-picking.md
  - 延迟着色法: 19-deferred-shading.md
  - 实例化渲染: 20-indirect-drawing.md
  - 间接绘制计算着色器: 21-indirect-drawing-and-copute-shaders.md
  - 附录 A - OpenGL调试: appendix-a.md
  # - 术语表: glossary.md

site_name: Lwjglbook中文翻译-笔记
site_author: Mouse0w0
copyright: 2025, yin2hao

repo_url: https://github.com/yin2hao/lwjglbook-CN-Translation
remote_branch: pages

theme:
  name: material
  icon:
    annotation: material/plus-circle-outline
    admonition:
      note: octicons/tag-16
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select

# extra_javascript:
#   - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic